import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/header'
import Navbar from '../components/navbar'
import NavbarVertical from '@/components/navbarVertical'
import Ticker from '@/components/ticker'
import Sponsors from '@/components/sponsors'
import Twitch from '@/components/twitchSection'
const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  return (
    <>
      <Head>
        <title>Jim Rising</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <main >
        <Header />
        <Ticker />
        <Sponsors />
        <Twitch />
      </main>
    </>
  )
}
